### ISSUE TITLE
404 error page

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#195]
the standard 404 error page has all the links pointing back to eclipse.org pages which should be openhwgroup.org pages...

https://www.openhwgroup.org/events/

**Comment by autumnfound** [comment]
Could you provide links that you would want to see on this page?

**Comment by rickoco** [comment]
> Could you provide links that you would want to see on this page?

The links would be the Events shown on the side bar of the home page https://www.openhwgroup.org/ similar in format to the News page https://www.openhwgroup.org/news/ and is accessed when the users clicks "View All" at the bottom of the Events side bar

**Comment by chrisguindon** [comment]
@rickoco Please see my comments below:

**1. Custom 404 page:**
We can definitely change the content of the 404 page. I would recommend keeping most of the content and replace Eclipse home with OpenHWGroup home.

It's important to understand that this file is served each time a user tries to access a url that does not exist. For example:
https://www.openhwgroup.org/this-page-does-not-exist

I am not convinced that adding events here make sense but we could probably do it if you want.

**1. https://www.openhwgroup.org/events/** 

We need to create an events page otherwise our Custom 404 is served to the user. Is that what you are asking?

**Comment by rickoco** [comment]
> @rickoco Please see my comments below:
> 
> **1. Custom 404 page:**
> We can change the content of the 404 page. I would recommend keeping most of the content and replace Eclipse home with OpenHWGroup home.
> 
> It's important to understand that this file is served each time a user tries to access a url that does not exist. For example:
> https://www.openhwgroup.org/this-page-does-not-exist
> 
> I am not convinced that adding events here make sense but we could probably do it if you want.
> 
> **2. https://www.openhwgroup.org/events/**
> 
> We need to create an events page otherwise our Custom 404 is served to the user. Is that what you are asking?

Yes, see that is correct.  See [issue 196](https://github.com/openhwgroup/openhwgroup.org/issues/196#issue-651769830)
