### ISSUE TITLE
Members & Partners link broken?

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#219]
It appears this link is broken and doesn't navigate right to the Members & Partners section (tested in both Safari and Chrome)

https://www.openhwgroup.org/#members-partners

**Comment by autumnfound** [comment]
Whats the context, what link is broken, on which page?

**Comment by chrisguindon** [comment]
> It appears this link is broken and doesn't navigate right to the Members & Partners section (tested in both Safari and Chrome)
> 
> https://www.openhwgroup.org/#members-partners

This is an anchor link. An anchor link is a web link that allows users to jump to a specific point on a website page. For this link, I would expect this to go to the section on the homepage that id value of  "members-partners".

Closing this issues since this seems to work as expected!

**Comment by rickoco** [comment]
So, I’ve found the anchor link is fine on Chrome running on a MacBook Pro, but not Safari on the MacBook and also not for Chrome or Safari on iPad Pro.

**Comment by autumnfound** [comment]
The only place I see that URL is in a news article from February (when that URL was more actively used), and on Futurewei (who never provided a URL, and was set a such to avoid a redirect issue). In the case of the second case, we could update the link. Where are you encountering this issue otherwise?

In terms of the actual issue, this seems to be an issue that users encounter on Apple devices, and the cause isn't known and has been an issue for nearly a decade according to some forums. For some pages, there is a solution, but homepages seem to be a sticking point in some cases.

The only solution that might work would be to force it to directly link to the implied homepage at `/index.html`. See below for the link example of this.
https://www.openhwgroup.org/index.html#members-partners

**Comment by chrisguindon** [comment]
> So, I’ve found the anchor link is fine on Chrome running on a MacBook Pro, but not Safari on the MacBook and also not for Chrome or Safari on iPad Pro.

You are right! I can reproduce this problem with Safari as-well.

**Comment by rickoco** [comment]
@autumnfound - we use the link extensively in outreach emails promoting OpenHW Group membership as part of our recruiting efforts.  Whatever works cross platform that lets us link directly to the logo roster is what I’m looking for.

**Comment by autumnfound** [comment]
Give https://www.openhwgroup.org/index.html#members-partners a whirl on those platforms. I've double-checked and it works for Chrome and Firefox on my end, and Chris checked in Safari yesterday IIRC and it was alright. This isn't to do with our site, but rather a weirdness in how the browser handles anchors. There's no real solution here to solve this otherwise, as we are implementing proper+compliant HTML for links like that

**Comment by autumnfound** [comment]
@rickoco did that link solve your issue?

**Comment by rickoco** [comment]
sorry @autumnfound - safari on iPad doesn’t work

**Comment by linkfang** [comment]
I just tested on my iPad using Safari, looks like the issue is resolved on their end.

For me, both https://www.openhwgroup.org/index.html#members-partners and https://www.openhwgroup.org/#members-partners work well.

@rickoco is any of them working on your end?

**Comment by rickoco** [comment]
yes - I believe this is resolved now.  thank you :-)
