### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#27]
https://www.openhwgroup.org/categories/events/

should read...
Join us at the FOSSi Foundation Week of Open Source Hardware (WOSH) including the RISC-V Workshop in Zurich, June 11-14, 2019 to learn more about the OpenHW Group CORE-V Family of open-source RISC-V cores and contribute to the evolution of open-source processor core development.

**Comment by ericpoirier** [comment]
Hi Rick,

Here a brief description of how the events have been configured in the theme we have created for all our sites:

On the home page we show the 5 most recent events and on the events page, we display them all and we display the same information.

I can update that theme to match this new requirement for your site but that will require some time and I saw that you opened a lot of issues yesterday. I haven't had the chance to look at them all but I'll assess the priorities and go from there since it all needs to be done by the end of the day.

**Comment by ericpoirier** [comment]
Hi Rick, I was able to clear all the other issues pretty quickly, I'll have a look at this one so that on the events page we have more information

**Comment by ericpoirier** [comment]
Hi Rick,

I was able to change this pretty easily actually. It was already printing a generic description which I updated to what you wanted and I updated the layout so it matches to the rest of the site.

Let me know if there's anything else.
