### ISSUE TITLE
OpenHW DV Con participation plus media coverage news

### ISSUE THREAD

**Issue by NaylDSouza** [openhwgroup/openhwgroup.org#271]
//Please can you add this story on the news page of OpenHWGroup website (https://www.openhwgroup.org/) in the News section just above the New episode of OpenHW TV (Season 2) available to watch) story. Thanks.
If you can add the first story on DV Con for the front page and then link to a separate news page linking to (https://www.openhwgroup.org/news) with this and the other two stories too. Thanks//

**OpenHW Group at the virtual DVCon, March 1 – 4 2021**

![DV-CON-logo](https://user-images.githubusercontent.com/74318457/107096043-c1c37400-6801-11eb-9098-34d276136361.jpg)

Presentation: 'Jump start your RISC-V project with OpenHW'
The OpenHW Group are joined by Imperas, Futurewei, Silicon Labs and EM Microelectronic.
This paper will address the verification methodology adopted by the OpenHW Verification Task Group to assure commercial standards for quality. Attendees will obtain the ability to use the OpenHW verification environment as a baseline to design and verify a custom RISCV core with their own value-add features. 

About DVCon 2021
For more information, visit the [event website](https://2021.dvcon.org)

**OpenHW Group video interview with EDACafe**
What does OpenHW provide to its members that they can’t necessarily do by themselves, and are there any other member benefits that are particularly compelling? And what can we expect to look forward to seeing the organization achieve in 2021? EDACafe quizzes Rick O'Connor to find out more.
[View the video](https://www.edacafe.com/video/OpenHW-Group-Rick-O39;Connor-Founder-CEO/1379978/media.html )

**Feature in Semiconductor Engineering**
Finally, a suggestion to read [this article](https://semiengineering.com/risc-v-becoming-less-risky-with-the-right-verification) by Rob Van Blommestein at OneSpin Solutions in Semiconductor Engineering on RISC-V Becoming less Risky With The Right Verification.

**Comment by flora8984461** [comment]
@chrisguindon I think this requires we add these three stories into newroom news?

**Comment by NaylDSouza** [comment]
Hi @flora8984461 and @chrisguindon, I'd be happy just to have the two stories - you can join the EDA Cafe and Feature in Semiconductor Engineering together under the headline 'Latest media coverage news' if that helps.

**Comment by chrisguindon** [comment]
@NaylDSouza We can definitely create a new article on the website to host the content for "OpenHW Group at the virtual DVCon, March 1 – 4 2021". We will also submit the article to our Newsroom website in order for this to show on our homepage and /news.

However,  you don't need our help for "OpenHW Group video interview with EDACafe" and "Feature in Semiconductor Engineering" since you can submit those articles now to our Newsroom website now since they don't need it's own article as they are external link: https://newsroom.eclipse.org/node/add/news

**Comment by chrisguindon** [comment]
@NaylDSouza Unless you expect us to add all of this content under the same new article. Please confirm.

**Comment by NaylDSouza** [comment]
It would work under one article too. Thanks @chrisguindon

**Comment by flora8984461** [comment]
Hi @NaylDSouza please check the preview: https://deploy-preview-275--eclipsefdn-openhwgroup.netlify.app/news/2021/02/08/openhw-group-at-the-virtual-dvcon-march-1-4-2021/

Once we got +1 from you, we will merge to live and create a news in the newroom and pointing to this page.

Thanks!

**Comment by NaylDSouza** [comment]
@flora8984461 @chrisguindon 
+1 
But please can you ensure that this story precedes the news on the webinar registration – otherwise the webinar news will be lower in chronological order and not be deemed as new or as important. I want to keep the webinar registration pinned to the top until the 18 February. Thanks

**Comment by chrisguindon** [comment]
`But please can you ensure that this story precedes the news on the webinar registration – otherwise the webinar news will be lower in chronological order and not be deemed as new or as important. I want to keep the webinar registration pinned to the top until the 18 February. `

@NaylDSouza Now sure we understand.

We need to submit the article to the newsroom to show them on the homepage. News are ordered by date.  We can submit this one last to make sure it's the last one.

**Comment by flora8984461** [comment]
@chrisguindon  @NaylDSouza  If I understand correctly, we need to make https://github.com/openhwgroup/openhwgroup.org/issues/273 the latest / newest? So that it will be on the top.

**Comment by NaylDSouza** [comment]
Correct @flora8984461 - please make #273 the latest / newest? So that it will be on the top. Cheers. And thanks @chrisguindon for the speedy reply too.

**Comment by flora8984461** [comment]
@NaylDSouza 
Please check the two new news here:
https://www.openhwgroup.org/news/

thanks!
