### ISSUE TITLE
OpenHW events page - 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#398]
i'm looking to find when the next episode of open HW TV will be posted.  The request was submitted earlier in the week. please let me know if I need to resubmit

**Comment by chrisguindon** [comment]
@michelleclancy Did you create an issue asking us to post this episode? I can't find it in our queue: https://github.com/openhwgroup/openhwgroup.org/issues

**Comment by michelleclancy** [comment]
@chrisguindon actually i thought i did, but i did not hit the submit button.. then I resubmitted and it's up. thanks

**Comment by chrisguindon** [comment]
I am confused, I don't see an issue. We can use this one for this purpose if you.  Looking at an existing open HW TV page, this is the info we need in order to create a page:

title: 
date: 
episode_title:
season: 
Description:
youku.com URL:
youtube URL:

You can refer to this existing page as a reference to what we need:
https://raw.githubusercontent.com/openhwgroup/openhwgroup.org/master/content/resources/openhwtv/s01e01.md

Let us know if you have any questions!

**Comment by michelleclancy** [comment]
sorry @chrisguindon there is no issue, there is no longer an issue. I don't know how to use Github, so i don't know how to remove an issue that is resolved.
