### ISSUE TITLE
OpenHW Group press release for News Page 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#641]
hi all, I submitted this release to the News submissions page, but wanted to make sure it was received. We would like to make this announcement tomorrow Wednesday August 16 - if we can have this release posted by tomorrow, August 16th, it would be appreciated. 
[v3 OpenHW CORE-V MCU Press Release_8.8 DRAFT.docx](https://github.com/openhwgroup/openhwgroup.org/files/12346170/v3.OpenHW.CORE-V.MCU.Press.Release_8.8.DRAFT.docx)
![UPDATED MCU DevKit](https://github.com/openhwgroup/openhwgroup.org/assets/88848029/a6f0a617-943d-4c8d-aedb-71ce467be25a)

**Comment by oliviergoulet5** [comment]
Hi @michelleclancy, I will get working on this!

As for the news submission, we only need to submit once the page is live on https://openhwgroup.org. The article needs to exist and have a URL before we submit it to the newsroom.

**Comment by michelleclancy** [comment]
@oliviergoulet5 thanks!  sorry for the confusion on the newsroom.  We want to announce tomorrow and it would be nice to have it on the site. Best, Michelle

**Comment by oliviergoulet5** [comment]
@michelleclancy Here is a preview: https://preview-642--openhwgroup-org.eclipsecontent.org/resources/blog/

Once approved by you, I will deploy and submit through newsroom. Just to confirm: should I set you as the author?

**Comment by oliviergoulet5** [comment]
@michelleclancy It should when I submit it and they get it approved. 

There is some bad news though... the newsroom is currently down. [See status](https://www.eclipsestatus.io/).

The least I can do right now is just push live with the page only linked to https://openhwgroup.org/resources/blog.

I'll submit it through newsroom immediately when it is back up.

**Comment by rickoco** [comment]
@oliviergoulet5 - can you please "unpin" the CEO post now? https://www.openhwgroup.org/resources/blog/openhw-group-seeking-ceo/

**Comment by michelleclancy** [comment]
@oliviergoulet5 still don't see the press release blog on the blog page??

**Comment by oliviergoulet5** [comment]
@michelleclancy There's nothing I can do at the moment as there are infra issues right now and some services we rely upon are down. Including what we use for website deployments.

I did notice the newsroom is back up and your submission was accepted: https://newsroom.eclipse.org/news/community-news/openhw-group-announces-tape-out-risc-v-based-core-v-mcu-development-kit-iot.

The content is hosted on newsroom.eclipse.org instead of openhwgroup.org. It is also linked on the frontpage of openhwgroup.org. Is this good enough for now?

Once our services are back up we can link that newsroom post to the version hosted on openhwgroup.org.

**Comment by michelleclancy** [comment]
@oliviergoulet5 yes the locations on the website for news are good. As soon as they are up, can you let me know? I keep checking but it's not live yet, we'd like to start to push out on social.

**Comment by oliviergoulet5** [comment]
@michelleclancy Sorry for the unexpected delays.

Everything is up now. The news section on homepage links to the correct page.
