### ISSUE TITLE
Add RedHat News blurb

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#674]
On www.openhwgroup.org under "News" please add the following item. This one needs review from @michelleclancy and @Floadv298 and @Jefro-redhat before deployment.
thanks
Duncan

Dec 1, 2023 
Red Hat Joins OpenHW Group to Help Drive Fully-Open SOC Designs

OpenHW Group is pleased to welcome Red Hat, a leading provider of enterprise open source solutions, to the OpenHW Group community. "Red Hat has always been at the forefront supporting open technology efforts, and RISC-V presents an architecture that can help drive a new wave of open innovation. We look forward to continuing our work with the OpenHW Group and the surrounding ecosystem, especially with OpenHW Group’s drive towards fully-open SOC designs.", said Ronald Pacheco, Senior Director, Linux Business & Ecosystem Strategy. "OpenHW Group anticipates that RedHat will make major contributions to our efforts to drive software deployment on open-source processors, leading to great benefits for the RISC-V industry as a whole", said Flo Wohlrab, CEO of OpenHW Group.

**Comment by DBees** [comment]
Putting this on hold pending discussion with @michelleclancy @Floadv298

**Comment by DBees** [comment]
@oliviergoulet5 it was decided to go ahead with this one. Can you please action this now? You can backdate to Dec 1 as originally indicated. 
thanks
Duncan

**Comment by oliviergoulet5** [comment]
@DBees here is a preview: https://preview-681--openhwgroup-org.eclipsecontent.org/news/2023/12/01/red-hat-joins-openhw-group-to-help-drive-fully-open-soc-designs/

I modified the content slightly to use block quotes instead of inline quotes. I thought it would be more visually interesting for a webpage. Let me know if I should revert to the original.

**Comment by oliviergoulet5** [comment]
@DBees have you had the chance to look?

cc @michelleclancy

**Comment by DBees** [comment]
@oliviergoulet5 apology. The indent with grey bars looks a bit dramatic. I would just put the quotation in quotes. 
Duncan

**Comment by Floadv298** [comment]
LGTM shoudl be ok to go online (last link 681 preview)

**Comment by oliviergoulet5** [comment]
I am using quotes now. I will put the patch under review with the webdev team, and then I'll submit the post to the Eclipse Newsroom so that it will appear on the homepage.

**Comment by oliviergoulet5** [comment]
On second thought, I'll let one of you publish it. Otherwise, my name would be shown as the primary author. I believe @michelleclancy is familiar with the process.

You can submit the news item here: https://newsroom.eclipse.org/node/add/news

In the URL field, add: https://www.openhwgroup.org/news/2023/12/01/red-hat-joins-openhw-group-to-help-drive-fully-open-soc-designs/

You add the summary in the content box. I would put the first sentence, "OpenHW Group is pleased to welcome Red Hat, a leading provider of enterprise open source solutions, to the OpenHW Group community."

@DBees @michelleclancy @Floadv298

**Comment by DBees** [comment]
@oliviergoulet5 I'm not sure I follow these instructions. This is to be published on the OpenHW website, not the EF website. 
BTW for the time being Flo and I are handling these items.

**Comment by Floadv298** [comment]
Hi @oliviergoulet5 
I tried to follow your description:
https://newsroom.eclipse.org/news/announcements/red-hat-joins-openhw-group-help-drive-fully-open-soc-designs
Will it be on OpenHW? I clicked OpenHW explizite.

**Comment by oliviergoulet5** [comment]
@Floadv298 Yes it will. There is a moderation process. Once the content has been reviewed and accepted, it will be visible on the front page of OpenHW.
